FIO-8450: Fix custom error message for unique validation
formio/core pull request #106
Opened 2024-06-19 11:22 UTC by mikekotikov

## Link to Jira Ticket

https://formio.atlassian.net/browse/FIO-8450

## Description

**What changed?**

Custom validation error messages were not populated, this PR adds a fix

**Why have you chosen this solution?**

*Use this section to justify your choices*

## Breaking Changes / Backwards Compatibility

*Use this section to describe any potentially breaking changes this PR introduces or any effects this PR might have on backwards compatibility*

## Dependencies

*Use this section to list any dependent changes/PRs in other Form.io modules*

## How has this PR been tested?

Test is added on formio-server side

## Checklist:

- [] I have completed the above PR template
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings
- [x] My changes include tests that prove my fix is effective (or that my feature works as intended)
- [x] New and existing unit/integration tests pass locally with my changes
- [ ] Any dependent changes have corresponding PRs that are listed above

2024-06-21 14:41 UTC, brendanbond requested changes
Let me know your thoughts

2024-06-21 14:41 UTC, brendanbond commented on src/process/validation/util.ts
> +const getCustomErrorMessage = ({ errorKeyOrMessage, context }: FieldError): string =>
I'm not positive, but couldn't this be added to `getComponentErrorField`? the FieldError class already does a version of this, I'd like for this "error interpolation" stuff to all happen in one place

2024-06-28 09:17 UTC, mikekotikov commented
@brendanbond rechecked with the first commit implementation, this way any custom validation messages are applied (unique, required, min, max, etc.)

2024-06-29 03:44 UTC, brendanbond approved these changes

2024-06-29 03:44 UTC, merged