FIO-9485: fix conditionals path for panel component
formio/core pull request #207
Opened 2024-12-20 15:44 UTC by Maria-Golomb

## Link to Jira Ticket

https://formio.atlassian.net/browse/FIO-XXXX

## Description

**What changed?**

_Use this section to provide a summary description of the changes you've made_

**Why have you chosen this solution?**

_Use this section to justify your choices_

## Breaking Changes / Backwards Compatibility

_Use this section to describe any potentially breaking changes this PR introduces or any effects this PR might have on backwards compatibility_

## Dependencies

_Use this section to list any dependent changes/PRs in other Form.io modules_

## How has this PR been tested?

_Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning_

## Checklist:

- [ ] I have completed the above PR template
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] My changes generate no new warnings
- [ ] My changes include tests that prove my fix is effective (or that my feature works as intended)
- [ ] New and existing unit/integration tests pass locally with my changes
- [ ] Any dependent changes have corresponding PRs that are listed above

2024-12-30 15:55 UTC, brendanbond requested changes

2024-12-30 15:55 UTC, brendanbond commented on src/process/conditions/index.ts
> +    conditionalComp = {
something seems fishy to me about this change. Why wouldn't one of the new pathing options work here for Panel? (i.e. `fullPath` or `fullDataPath` etc.)?

2025-01-07 14:17 UTC, Maria-Golomb commented on src/process/conditions/index.ts
> +    conditionalComp = {
Agree. Fixed.

2025-01-07 17:02 UTC, brendanbond approved these changes

2025-01-07 17:02 UTC, merged