FIO 7488: improve error handling
formio/core pull request #59
Opened 2024-03-19 09:31 UTC by brendanbond

## Link to Jira Ticket

https://formio.atlassian.net/browse/FIO-7488

## Description

Replaces `ValidatorError` and `DereferenceError` with a more generic `ProcessorError`
 
## Breaking Changes / Backwards Compatibility

n/a

## Dependencies

n/a

## How has this PR been tested?

n/a

## Checklist:

- [x] I have completed the above PR template
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings
- [ ] My changes include tests that prove my fix is effective (or that my feature works as intended)
- [x] New and existing unit/integration tests pass locally with my changes
- [ ] Any dependent changes have corresponding PRs that are listed above

2024-04-05 14:02 UTC, AlexeyNikipelau commented on src/process/validation/rules/validateAvailableItems.ts
> +            throw new Error(
Why not use ProcessorError here?

2024-04-08 16:09 UTC, brendanbond commented on src/process/validation/rules/validateAvailableItems.ts
> +            throw new Error(
whoopsie, fixed

2024-04-11 13:51 UTC, AlexeyNikipelau requested changes

2024-04-11 13:51 UTC, AlexeyNikipelau commented on src/process/validation/rules/validateMinimumSelectedCount.ts
> +        throw new Error(
And here

2024-04-11 13:51 UTC, AlexeyNikipelau commented on src/process/validation/rules/validateMaximumSelectedCount.ts
> -        throw new ValidatorError(
Also here

2024-04-17 12:49 UTC, merged